# Utiliser une image de base avec Rust
FROM rust:1.72-slim

# Installer le package CLI de postman2openapi via Cargo
RUN cargo install postman2openapi-cli

# Créer un répertoire de travail
WORKDIR /app

