###
GET https://localhost



###
GET https://localhost/api/health
Content-Type: application/json;



###
POST https://localhost/api/user
Content-Type: application/json;

{
  "login":"j-f",
  "password": "test"
}