enum ERRORS {
  HELLO_USECASE_FAIL = 'HELLO_USECASE_FAIL',
  NO_FIELDS_TO_UPDATE = 'NO_FIELDS_TO_UPDATE',
  CONNECTION_DATABASE_FAIL = 'CONNECTION_DATABASE_FAIL',
  FILE_SIZE_LIMIT_EXCEEDED = 'FILE_SIZE_LIMIT_EXCEEDED',
  
  
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  LINK_NOT_FOUND = 'LINK_NOT_FOUND',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  REFERENCE_NOT_FOUND = 'REFERENCE_NOT_FOUND',

  ADD_FILE_CONTROLLER_FAIL = 'ADD_FILE_CONTROLLER_FAIL',
  GET_FILE_CONTROLLER_FAIL = 'GET_FILE_CONTROLLER_FAIL',
  GET_FILES_CONTROLLER_FAIL = 'GET_FILES_CONTROLLER_FAIL',
  PATCH_FILE_CONTROLLER_FAIL = 'PATCH_FILE_CONTROLLER_FAIL',
  REMOVE_FILE_CONTROLLER_FAIL = 'REMOVE_FILE_CONTROLLER_FAIL',
  REMOVE_HARD_FILE_CONTROLLER_FAIL = 'REMOVE_HARD_FILE_CONTROLLER_FAIL',
  GET_TOTAL_SIZE_FILE_CONTROLLER_FAIL = 'GET_TOTAL_SIZE_FILE_CONTROLLER_FAIL',

  CREATE_LINK_CONTROLLER_FAIL = 'CREATE_LINK_CONTROLLER_FAIL',

  
  ADD_REFERENCE_REPOSITORY_FAIL = 'ADD_REFERENCE_REPOSITORY_FAIL',
  GET_REFERENCE_REPOSITORY_FAIL = 'GET_REFERENCE_REPOSITORY_FAIL',
  GET_REFERENCES_REPOSITORY_FAIL = 'GET_REFERENCES_REPOSITORY_FAIL',
  PATCH_REFERENCE_REPOSITORY_FAIL = 'PATCH_REFERENCE_REPOSITORY_FAIL',
  REMOVE_REFERENCE_REPOSITORY_FAIL = 'REMOVE_REFERENCE_REPOSITORY_FAIL',
  GET_REFERENCES_WHERE_REPOSITORY_FAIL = 'GET_REFERENCES_WHERE_REPOSITORY_FAIL',
  
  ADD_FILE_REPOSITORY_FAIL = 'ADD_FILE_REPOSITORY_FAIL',
  GET_FILE_REPOSITORY_FAIL = 'GET_FILE_REPOSITORY_FAIL',
  GET_FILES_REPOSITORY_FAIL = 'GET_FILES_REPOSITORY_FAIL',
  PATCH_FILE_REPOSITORY_FAIL = 'PATCH_FILE_REPOSITORY_FAIL',
  REMOVE_FILE_REPOSITORY_FAIL = 'REMOVE_FILE_REPOSITORY_FAIL',
  GET_FILE_WHERE_REPOSITORY_FAIL = 'GET_FILE_WHERE_REPOSITORY_FAIL',
  REMOVE_HARD_FILE_REPOSITORY_FAIL = 'REMOVE_HARD_FILE_REPOSITORY_FAIL',
  GET_TOTAL_FILES_SIZE_BY_USER_REPOSITORY_FAIL = 'GET_TOTAL_FILES_SIZE_BY_USER_REPOSITORY_FAIL',
  
  ADD_LINK_REPOSITORY_FAIL = 'ADD_LINK_REPOSITORY_FAIL',
  GET_LINK_REPOSITORY_FAIL = 'GET_LINK_REPOSITORY_FAIL',
  GET_LINKS_REPOSITORY_FAIL = 'GET_LINKS_REPOSITORY_FAIL',
  GET_LINKS_WHERE_REPOSITORY_FAIL = 'GET_LINKS_WHERE_REPOSITORY_FAIL',
  
}

export default ERRORS; 