enum ERRORS {
  NO_FIELDS_TO_UPDATE = 'NO_FIELDS_TO_UPDATE',
  CONNECTION_DATABASE_FAIL = 'CONNECTION_DATABASE_FAIL',

  
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  CURRENT_USER_NOT_FOUND = 'CURRENT_USER_NOT_FOUND',

  // MIDDLEWARE
  // Auth 
  AUTH_MIDDLEWARE_FAIL = 'AUTH_MIDDLEWARE_FAIL',
  
  // CONTROLLER
  // File
  READ_FILE_CONTROLLER_FAIL = 'READ_FILE_CONTROLLER_FAIL',
  CREATE_FILE_CONTROLLER_FAIL = 'CREATE_FILE_CONTROLLER_FAIL',
  UPDATE_FILE_CONTROLLER_FAIL = 'UPDATE_FILE_CONTROLLER_FAIL',
  DELETE_FILE_CONTROLLER_FAIL = 'DELETE_FILE_CONTROLLER_FAIL',
  DOWNLOAD_FILE_CONTROLLER_FAIL = 'DOWNLOAD_FILE_CONTROLLER_FAIL',
  READ_FILE_LIST_CONTROLLER_FAIL = 'READ_FILE_LIST_CONTROLLER_FAIL',
  DELETE_HARD_FILE_CONTROLLER_FAIL = 'DELETE_HARD_FILE_CONTROLLER_FAIL',
  READ_TOTAL_SIZE_FILE_CONTROLLER_FAIL = 'READ_TOTAL_SIZE_FILE_CONTROLLER_FAIL',
  READ_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND = 'READ_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND',
  CREATE_FILE_CONTROLLER_FAIL_HASHING_FAIL = 'CREATE_FILE_CONTROLLER_FAIL_HASHING_FAIL',
  UPDATE_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND = 'UPDATE_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND',
  DELETE_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND = 'DELETE_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND',
  DELETE_FILE_CONTROLLER_FAIL_FILE_NOT_DELETED = 'DELETE_FILE_CONTROLLER_FAIL_FILE_NOT_DELETED',
  DOWNLOAD_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND = 'SHARE_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND',
  DELETE_HARD_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND = 'DELETE_HARD_FILE_CONTROLLER_FAIL_FILE_NOT_FOUND',  
  DELETE_HARD_FILE_CONTROLLER_FAIL_FILE_NOT_DELETED = 'DELETE_HARD_FILE_CONTROLLER_FAIL_FILE_NOT_DELETED', 
  CREATE_FILE_CONTROLLER_FAIL_FILE_SIZE_LIMIT_EXCEEDED = 'CREATE_FILE_CONTROLLER_FAIL_FILE_SIZE_LIMIT_EXCEEDED',

  // Auth
  AUTH_CONTROLLER_FAIL = 'AUTH_CONTROLLER_FAIL',

  // User
  CREATE_USER_CONTROLLER_FAIL = 'CREATE_USER_CONTROLLER_FAIL',

  // Link
  CREATE_LINK_CONTROLLER_FAIL = 'CREATE_LINK_CONTROLLER_FAIL',
  READ_LINK_LIST_CONTROLLER_FAIL = 'READ_LINK_LIST_CONTROLLER_FAIL',
  CREATE_LINK_CONTROLLER_FAIL_FILE_NOT_FOUND='CREATE_LINK_CONTROLLER_FAIL_FILE_NOT_FOUND',
  CREATE_LINK_CONTROLLER_FAIL_LINK_ALREADY_EXIST='CREATE_LINK_CONTROLLER_FAIL_LINK_ALREADY_EXIST',
  CREATE_LINK_CONTROLLER_FAIL_REFERENCE_NOT_FOUND='CREATE_LINK_CONTROLLER_FAIL_REFERENCE_NOT_FOUND',

  // Share file with link 
  SHARE_FILE_WITH_LINK_CONTROLLER_FAIL = 'SHARE_FILE_WITH_LINK_CONTROLLER_FAIL',
  SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_LINK_EXPIRED = 'SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_LINK_EXPIRED',
  SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_INVALID_TOKEN = 'SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_INVALID_TOKEN',
  SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_TOKEN_EXPIRED = 'SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_TOKEN_EXPIRED',
  SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_LINK_NOT_FOUND = 'SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_LINK_NOT_FOUND',
  SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_FILE_NOT_FOUND = 'SHARE_FILE_WITH_LINK_CONTROLLER_FAIL_FILE_NOT_FOUND',

  
  // REPOSITORY
  // User
  INSERT_USER_REPOSITORY_FAIL = 'INSERT_USER_REPOSITORY_FAIL',
  SELECT_USER_REPOSITORY_FAIL = 'SELECT_USER_REPOSITORY_FAIL',
  SELECT_USER_BY_LOGIN_REPOSITORY_FAIL = 'SELECT_USER_BY_LOGIN_REPOSITORY_FAIL',
  INSERT_USER_REPOSITORY_FAIL_TO_ACCES_USER = 'INSERT_USER_REPOSITORY_FAIL_TO_ACCES_USER',
  INSERT_USER_REPOSITORY_FAIL_USER_ALREADY_EXIT = 'INSERT_USER_REPOSITORY_FAIL_USER_ALREADY_EXIT',
  
  // File
  INSERT_FILE_REPOSITORY_FAIL = 'INSERT_FILE_REPOSITORY_FAIL',
  UPDATE_FILE_REPOSITORY_FAIL = 'UPDATE_FILE_REPOSITORY_FAIL',
  SELECT_FILE_REPOSITORY_FAIL = 'SELECT_FILE_REPOSITORY_FAIL',
  DELETE_FILE_REPOSITORY_FAIL = 'DELETE_FILE_REPOSITORY_FAIL',
  SELECT_FILE_LIST_REPOSITORY_FAIL = 'SELECT_FILE_LIST_REPOSITORY_FAIL',
  SELECT_EXTEND_FILE_REPOSITORY_FAIL = 'SELECT_EXTEND_FILE_REPOSITORY_FAIL',
  SELECT_FILE_LIST_WHERE_REPOSITORY_FAIL = 'SELECT_FILE_LIST_WHERE_REPOSITORY_FAIL',
  UPDATE_REVOKED_AT_FILE_REPOSITORY_FAIL = 'UPDATE_REVOKED_AT_FILE_REPOSITORY_FAIL',
  INSERT_FILE_REPOSITORY_FAIL_TO_ACCES_FILE = 'INSERT_FILE_REPOSITORY_FAIL_TO_ACCES_FILE',
  UPDATE_FILE_REPOSITORY_FAIL_TO_ACCES_FILE = 'UPDATE_FILE_REPOSITORY_FAIL_TO_ACCES_FILE',
  SELECT_TOTAL_FILES_SIZE_BY_USER_REPOSITORY_FAIL = 'SELECT_TOTAL_FILES_SIZE_BY_USER_REPOSITORY_FAIL',
  UPDATE_REVOKED_AT_FILE_REPOSITORY_FAIL_TO_ACCES_FILE = 'UPDATE_REVOKED_AT_FILE_REPOSITORY_FAIL_TO_ACCES_FILE',

  // Reference
  INSERT_REFERENCE_REPOSITORY_FAIL = 'INSERT_REFERENCE_REPOSITORY_FAIL',
  UPDATE_REFERENCE_REPOSITORY_FAIL = 'UPDATE_REFERENCE_REPOSITORY_FAIL',
  DELETE_REFERENCE_REPOSITORY_FAIL = 'DELETE_REFERENCE_REPOSITORY_FAIL',
  SELECT_REFERENCE_REPOSITORY_FAIL = 'SELECT_REFERENCE_REPOSITORY_FAIL',
  SELECT_REFERENCE_LIST_REPOSITORY_FAIL = 'SELECT_REFERENCE_LIST_REPOSITORY_FAIL',
  SELECT_REFERENCE_LIST_WHERE_REPOSITORY_FAIL = 'SELECT_REFERENCE_LIST_WHERE_REPOSITORY_FAIL',
  INSERT_REFERENCE_REPOSITORY_FAIL_TO_ACCES_REFERENCE = 'INSERT_REFERENCE_REPOSITORY_FAIL_TO_ACCES_REFERENCE',
  
  // Link
  INSERT_LINK_REPOSITORY_FAIL = 'INSERT_LINK_REPOSITORY_FAIL',
  SELECT_LINK_REPOSITORY_FAIL = 'SELECT_LINK_REPOSITORY_FAIL',
  SELECT_LINK_LIST_REPOSITORY_FAIL = 'SELECT_LINK_LIST_REPOSITORY_FAIL',
  SELECT_LINK_LIST_WHERE_REPOSITORY_FAIL = 'SELECT_LINK_LIST_WHERE_REPOSITORY_FAIL',
  INSERT_LINK_REPOSITORY_FAIL_TO_ACCES_LINK = 'INSERT_LINK_REPOSITORY_FAIL_TO_ACCES_LINK',
}

export default ERRORS; 