enum ERRORS {
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  HELLO_USECASE_FAIL = 'HELLO_USECASE_FAIL',
  CONNECTION_DATABASE_FAIL = 'CONNECTION_DATABASE_FAIL',


  ADD_FILE_REPOSITORY_FAIL = 'ADD_FILE_REPOSITORY_FAIL',
  GET_FILE_REPOSITORY_FAIL = 'GET_FILE_REPOSITORY_FAIL',
  GET_FILES_REPOSITORY_FAIL = 'GET_FILES_REPOSITORY_FAIL',
  PATCH_FILE_REPOSITORY_FAIL = 'PATCH_FILE_REPOSITORY_FAIL',
  REMOVE_FILE_REPOSITORY_FAIL = 'REMOVE_FILE_REPOSITORY_FAIL',

  ADD_FILE_CONTROLLER_FAIL = 'ADD_FILE_CONTROLLER_FAIL',
  GET_FILE_CONTROLLER_FAIL = 'GET_FILE_CONTROLLER_FAIL',
  GET_FILES_CONTROLLER_FAIL = 'GET_FILES_CONTROLLER_FAIL',
  PATCH_FILE_CONTROLLER_FAIL = 'PATCH_FILE_CONTROLLER_FAIL',
  REMOVE_FILE_CONTROLLER_FAIL = 'REMOVE_FILE_CONTROLLER_FAIL',
}

export default ERRORS; 